name: tasc_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning thông tin cho ứng dụng.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Thư viện phụ thuộc chính cho Flutter ứng dụng.
dependencies:
  flutter:
    sdk: flutter

  # Biểu tượng phong cách iOS, dùng cho các ứng dụng có giao diện giống iOS.
  cupertino_icons: ^1.0.8
  http: ^0.13.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: gợi ý các quy tắc tốt trong việc viết mã.
  flutter_lints: ^4.0.0

# Phần này dành riêng cho các dự án Flutter.
flutter:
  # Bao gồm các biểu tượng Material Icons trong ứng dụng.
  uses-material-design: true

  # Để thêm các tệp tài sản vào ứng dụng của bạn, hãy thêm phần assets, ví dụ:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Phần font custom: Nếu bạn muốn thêm phông chữ tùy chỉnh vào dự án, bạn có thể sử dụng đoạn mã mẫu sau:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
